#%RAML 1.0 NamedExample
values:
  [
    {
        "BillingCountry": "Canada",
        "BillingCity": "citycity 2",
        "BillingStreet": "213 streename 2",
        "Phone": ,
        "BillingPostalCode": "l3dd2f",
        "Id": "0010b00002CRBroAAH",

        "BillingState": "statestate 2",
        "Name": "Foo Bar Mule"
    },
    {
        "BillingCountry": "canada",
        "BillingCity": "citycity",
        "BillingStreet": "213 streename",
        "Phone": ,
        "BillingPostalCode": "l3dd2f",
        "Id": "0010b00002CRBrnAAH",

        "BillingState": "statestate",
        "Name": "Foo Bar Mule"
    },
    {
        "BillingCountry": "Canada",
        "BillingCity": "citycity 2",
        "BillingStreet": "213 streename 2",
        "Phone": ,
        "BillingPostalCode": "l3dd2f",
        "Id": "0010b00002CRBrpAAH",

        "BillingState": "statestate",
        "Name": "Chatter Expert"
    },
    {
        "BillingCountry": "USA",
        "BillingCity": "Burlington",
        "BillingStreet": "525 S. Lexington Ave",
        "Phone": "(336) 222-7000",
        "BillingPostalCode": "27215",
        "Id": "0010b00002BKIQgAAP",

        "BillingState": "NC",
        "Name": "Burlington Textiles Corp of America"
    },
    {
        "BillingCountry": "France",
        "BillingCity": "Paris",
        "BillingStreet": "2 Place Jussieu",
        "Phone": "(014) 427-4427",
        "BillingPostalCode": "75251",
        "Id": "0010b00002BKIQhAAP",

        "BillingState": ,
        "Name": "Pyramid Construction Inc."
    },
    {
        "BillingCountry": "USA",
        "BillingCity": "Lawrence",
        "BillingStreet": "1301 Hoch Drive",
        "Phone": "(785) 241-6200",
        "BillingPostalCode": "66045",
        "Id": "0010b00002BKIQiAAP",

        "BillingState": "KS",
        "Name": "Dickenson plc"
    },
    {
        "BillingCountry": ,
        "BillingCity": "Chicago",
        "BillingStreet": "2334 N. Michigan Avenue, Suite 1500\nChicago, IL 60601, USA",
        "Phone": "(312) 596-1000",
        "BillingPostalCode": ,
        "Id": "0010b00002BKIQjAAP",

        "BillingState": "IL",
        "Name": "Grand Hotels & Resorts Ltd"
    },
    {
        "BillingCountry": ,
        "BillingCity": "Portland",
        "BillingStreet": "620 SW 5th Avenue Suite 400\nPortland, Oregon 97204\nUnited States",
        "Phone": "(503) 421-7800",
        "BillingPostalCode": ,
        "Id": "0010b00002BKIQlAAP",

        "BillingState": "OR",
        "Name": "Express Logistics and Transport"
    },
    {
        "BillingCountry": ,
        "BillingCity": "Tucson",
        "BillingStreet": "888 N Euclid \nHallis Center, Room 501\nTucson, AZ 85721\nUnited States",
        "Phone": "(520) 773-9050",
        "BillingPostalCode": ,
        "Id": "0010b00002BKIQmAAP",

        "BillingState": "AZ",
        "Name": "University of Arizona"
    },
    {
        "BillingCountry": ,
        "BillingCity": "New York",
        "BillingStreet": "1301 Avenue of the Americas \nNew York, NY 10019\nUSA",
        "Phone": "(212) 842-5500",
        "BillingPostalCode": ,
        "Id": "0010b00002BKIQkAAP",

        "BillingState": "NY",
        "Name": "United Oil & Gas Corp."
    },
    {
        "BillingCountry": "US",
        "BillingCity": "San Francisco",
        "BillingStreet": "The Landmark @ One Market",
        "Phone": "(415) 901-7000",
        "BillingPostalCode": "94087",
        "Id": "0010b00002BKIQqAAP",

        "BillingState": "CA",
        "Name": "sForce"
    },
    {
        "BillingCountry": ,
        "BillingCity": "Austin",
        "BillingStreet": "312 Constitution Place\nAustin, TX 78767\nUSA",
        "Phone": "(512) 757-6000",
        "BillingPostalCode": ,
        "Id": "0010b00002BKIQfAAP",

        "BillingState": "TX",
        "Name": "Edge Communications"
    },
    {
        "BillingCountry": ,
        "BillingCity": "Singapore",
        "BillingStreet": "9 Tagore Lane\nSingapore, Singapore 787472\nSingapore",
        "Phone": "(650) 450-8810",
        "BillingPostalCode": ,
        "Id": "0010b00002BKIQoAAP",

        "BillingState": "Singapore",
        "Name": "United Oil & Gas, Singapore"
    },
    {
        "BillingCountry": ,
        "BillingCity": "Mountain View",
        "BillingStreet": "345 Shoreline Park\nMountain View, CA 94043\nUSA",
        "Phone": "(650) 867-3450",
        "BillingPostalCode": ,
        "Id": "0010b00002BKIQpAAP",

        "BillingState": "CA",
        "Name": "GenePoint"
    },
    {
        "BillingCountry": ,
        "BillingCity": ,
        "BillingStreet": "Kings Park, 17th Avenue, Team Valley Trading Estate,\nGateshead, Tyne and Wear NE26 3HS\nUnited Kingdom",
        "Phone": "+44 191 4956203",
        "BillingPostalCode": ,
        "Id": "0010b00002BKIQnAAP",

        "BillingState": "UK",
        "Name": "United Oil & Gas, UK"
    }
  ]