#%RAML 1.0 DataType
type: object
properties:
  Id?: string | nil
  Name: string
  BillingStreet: string
  BillingCountry?: string | nil
  BillingCity?: string | nil
  Phone?: string | nil
  BillingPostalCode?: string | nil
  BillingState?: string | nil