#%RAML 1.0 DataType
type: object
properties:
  id: string,
  name: string,
  city?: string | nil,
  street: string,
  state?: string | nil,
  phone?: string | nil,
  postalcode?: string | nil,
  country?: string | nil,
  lastSyncedTime: datetime