#%RAML 1.0 DataType
type: object
properties:
  Id?: string
  Name: string
  BillingStreet: string
  BillingCountry?: string
  BillingCity?: string
  Phone?: string
  BillingPostalCode?: string
  BillingState?: string