#%RAML 1.0 NamedExample
value: |   
  {
        "BillingCountry": "",
        "BillingCity": "Singapore",
        "BillingStreet": "9 Tagore Lane\nSingapore, Singapore 787472\nSingapore",
        "Phone": "(650) 450-8810",
        "BillingPostalCode": "",
        "BillingState": "Singapore",
        "Id" : "0010b00002CRBrnAAH",
        "Name": "United Oil & Gas, Singapore"
  }